set MATLAB=C:\Program Files\MATLAB\R2015b
g:\Tornado_vxWorks_221\host\x86-win32\bin\make -f Stromregler.mk  MULTI_INSTANCE_CODE=0 GENERATE_ASAP2=0 TMW_EXTMODE_TESTING=0 ISPROTECTINGMODEL=NOTPROTECTING
